### ISSUE TITLE
I get File Open Dialog and nothing else.

### ISSUE THREAD

**Issue by thinklog** [tedchoward/Frontier#3]
I am looking at OPML Editor v10.1b21for OS X (my OS X version is El Capitan). Once I launch OPML I the File Open Dialog, but there is no file to open. Once I close the File Open Dialog there is not much I can do. File -> New does not do anything, there is no window to enter anything, and the only thing I can do is Quit the application. That is also true for all the other version of OPML that I tried.

Am I missing something?

Thanks.

**Comment by tedchoward** [comment]
Did you download OPML.dmg from http://home.opml.org first?

That bundle contains lots of necessary files. You need to extract that first, and then replace opml.app with the version that you download here.

**Comment by thinklog** [comment]
Thanks. I didn't realize there was an opml.org website.

**Comment by tedchoward** [comment]
You're welcome. I should probably update the readme to include something about that.

**Comment by thinklog** [comment]
Great idea! That would indeed be helpful! Thanks again.
