### ISSUE TITLE
Mac OS El Capitan and Sierra support

### ISSUE THREAD

**Issue by pbreit** [tedchoward/Frontier#4]
A big ask but anyone more capable than me able to get this running on El Capitan or, better, Sierra?

**Comment by tedchoward** [comment]
The Yosemite build also runs on El Cap. I don't have a machine to install Sierra on for testing, but I imagine it works there as well.
Ted






On Wed, Aug 31, 2016 at 1:49 PM -0500, "Patrick Breitenbach" <notifications@github.com> wrote:












A big ask but anyone more capable than me able to get this running on El Capitan or, better, Sierra?
