### ISSUE TITLE
'Select a database file' - what to do?

### ISSUE THREAD

**Issue by applemyer** [tedchoward/Frontier#5]
Hi Ted,

Seems to be running fine on El Capitan. I just don't know what to do, exactly.

On first run it asks me to select a database file. It seems to need one  - I can't create a new document, if I just 'cancel'.

What is the database file, how do I select one that will let me progress?

Cheers,

David.

**Comment by tedchoward** [comment]
What you need to do is visit http://home.opml.org and download `OPML.dmg`. Drag the OPML folder inside that disk image to your `/Applications` folder. the `OPML` folder contains `OPML.app`. You need to replace that with the `OPML.app` that you downloaded from this Github repository. Now, when you launch `OPML.app`, it will automatically find the database file.

**Comment by applemyer** [comment]
Nice! That worked. Thanks Ted.

**Comment by tedchoward** [comment]
I added a "Full Distribution" download that includes everything you need to run the OPML Editor.

https://github.com/tedchoward/Frontier/releases/tag/v10.1b21
