### ISSUE TITLE
just keeps asking to "select a database file" on startup

### ISSUE THREAD

**Issue by eddo888** [tedchoward/Frontier#6]
Hi, this application does not work,
it just keeps asking to "select a database file" on startup,
I don't get to the OPML editor.
Mac OS High Sierra

**Comment by tedchoward** [comment]
Please take a look at issue #5 and see if that helps you.

**Comment by tedchoward** [comment]
I added a "Full Distribution" download that includes everything you need to run the OPML Editor.

https://github.com/tedchoward/Frontier/releases/tag/v10.1b21
