### ISSUE TITLE
"Full Distribution" Download Can't find opml.root

### ISSUE THREAD

**Issue by tedchoward** [tedchoward/Frontier#9]
For some reason, the "Full Distribution" download is unable to find `opml.root`.

Steps:
- Download `OPML-full-distribution.dmg`
- Double-click `OPML-full-distribution.dmg`
- Drag `OPML` folder to `/Applications`
- Double-click `/Applications/OPML.app`

Expected behavior:
- OPML editor launches and starts working

Actual behavior:
![screen shot 2018-04-27 at 5 28 53 pm](https://user-images.githubusercontent.com/470549/39387825-7a9b4bce-4a41-11e8-906c-b1a2f54130e8.png)

Workaround (launch from terminal):
- Launch Terminal.app
- type `cd ` and drag the `/Applications/OPML` folder to the terminal window
- type `./OPML.app/Contents/MacOS/OPML`
- Press return

I don't know why he workaround works and double-clicking the app bundle doesn't.

FWIW: The release works fine on my machine until I upload to Github. The files I download from Github have this problem.

**Comment by mrDarcyMurphy** [comment]
@tedchoward https://gist.github.com/mrDarcyMurphy/bc488c261883866ac504062ecc163bb3

I saw the same thing, so ran the app a few different ways and posted the logs to the gist above. Hope it helps.

**Comment by tedchoward** [comment]
@mrDarcyMurphy Thanks! I appreciate that.

I have a new workaround:

1. Download the "Full Distribution" DMG
2. Double-click `OPML-full-distribution.dmg`
3. Drag `OPML` folder somewhere (e.g. `/Applications`, the desktop)
4. Double-click `OPML` folder
5. Drag `OPML.app` to the Desktop
6. Drag `OPML.app` back to the `OPML` folder
7. Double-click `OPML.app`

**Comment by mrDarcyMurphy** [comment]
@tedchoward Cool. I'll try it out when I get the chance. In the meantime, I noticed you may have a hard coded path. Check [this line](https://gist.github.com/mrDarcyMurphy/bc488c261883866ac504062ecc163bb3#file-double-click-script-txt-L314).

**Comment by tedchoward** [comment]
- I had a theory that the application bundle was getting the wrong path.
- How does the kernel find the root database file?
  - Short answer: It looks in the same directory as the running application bundle.
- I published v10.2d4 which logs out the path to the application bundle when it tries to find the root database.
  - It confirmed my suspicions
  - `Apr 30 11:46:24 TedBook-Pro OPML[10764]: bundle url = file://localhost/var/folders/rw/2xy3lr9d0l7gvxprcm9vblth0000gn/T/AppTranslocation/FCD3E2C1-7C19-4010-896E-29F986FF2821/d/OPML.app/`
- It appears that macOS is copying the application to a "secure" location before executing it.
- Therefore the application can't find the root database file
- For some reason, copying the application bundle to a new location, and then copying it back causes macOS to stop doing this.

**Comment by tedchoward** [comment]
The "Security Feature" causing this headache is called App Translocation, and is part of macOS's Gatekeeper as of macOS 10.12 (Sierra)

https://weblog.rogueamoeba.com/2016/06/29/sierra-and-gatekeeper-path-randomization/

**Comment by tedchoward** [comment]
I'm going to close this issue, because there's nothing I can do about it.

I have updated the `README.md` file with instructions to download the `OPML` folder separately from the application bundle. This effectively works around the problem.

I have also removed all "Full Distribution" downloads from the Releases page.

**Comment by remorse** [comment]
I commented on another ticket about this, but in case it helps someone looking for a solution, you can do something like:

`````
Command to remove translocation from an application in Mac OS High Sierra

	xattr -dr com.apple.quarantine "/Applications/[application].app"
`````

to remove the app translocation from the application bundle. (Obviously, you would replace `[application]` with the name of the actual application...)

**Comment by maysonicboom** [comment]
It runs, but unable to open opml.root. Using the Terminal launch method workaround above, It aborts with following messages:

Maysons-iMac:OPML maysonlancaster$ ./OPML.app/Contents/MacOS/OPML
dyld: lazy symbol binding failed: Symbol not found: _OTLIFOStealList
  Referenced from: /Applications/OPML/./OPML.app/Contents/MacOS/OPML
  Expected in: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices

dyld: Symbol not found: _OTLIFOStealList
  Referenced from: /Applications/OPML/./OPML.app/Contents/MacOS/OPML
  Expected in: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices

Abort trap: 6

**Comment by maysonicboom** [comment]
Also, got the 32-bit (I believe) warning that it's not optimized and won't run in future versions.

**Comment by RoZZaH** [comment]
same warning as maysonicboom above..

**Comment by scripting** [comment]
Guys this isn't a bug report -- we know that Mojave is the last version of Mac OS that runs Frontier.

**Comment by RoZZaH** [comment]
Mojave... or do you mean High Sierra?
		

		
	





On Sun, Jan 20, 2019 at 5:30 PM +0000, "Dave Winer" <notifications@github.com> wrote:












Guys this isn't a bug report -- we know that Mojave is the last version of Mac OS that runs Frontier.

**Comment by tedchoward** [comment]
It runs on Mojave. It's a 32 bit app. Apple has told us that Mojave is the last version of macOS to support 32 bit apps.

**Comment by RoZZaH** [comment]
Ok - just checking - I may look at this again and revertThanks for clarifying Mojave not the issue.
		

		
	





On Mon, Jan 21, 2019 at 3:31 PM +0000, "Ted Howard" <notifications@github.com> wrote:












It runs on Mojave. It's a 32 bit app. Apple has told us that Mojave is the last version of macOS to support 32 bit apps.

**Comment by stemvork** [comment]
Crash upon launch after workaround by @tedchoward 

https://pastebin.com/Qh27AVxj
